name = "inceptra"
compatibility_date = "2024-04-03"
pages_build_output_dir = ".svelte-kit/cloudflare"

[[d1_databases]]
binding = "DB"
database_name = "inceptra-db"
database_id = "3b50bd54-9922-4391-b43c-53f169e3d3f0"

[[r2_buckets]]
binding = "BUCKET"
bucket_name = "inceptra-screenshots"
